"""Parsing prompts for Claude AI."""

from .parsing_prompts import (
    EMAIL_PARSING_PROMPT,
    EXCEL_PARSING_PROMPT,
    PPT_PARSING_PROMPT,
    IMAGE_PARSING_PROMPT,
    CHAT_PARSING_PROMPT,
    DOCUMENT_PARSING_PROMPT,
)

__all__ = [
    "EMAIL_PARSING_PROMPT",
    "EXCEL_PARSING_PROMPT",
    "PPT_PARSING_PROMPT",
    "IMAGE_PARSING_PROMPT",
    "CHAT_PARSING_PROMPT",
    "DOCUMENT_PARSING_PROMPT",
]
