"""TRD generation prompts."""

from .trd_prompts import (
    TECHNOLOGY_STACK_PROMPT,
    SYSTEM_ARCHITECTURE_PROMPT,
    DATABASE_DESIGN_PROMPT,
    API_SPECIFICATION_PROMPT,
    TRD_SUMMARY_PROMPT,
    SECURITY_REQUIREMENTS_PROMPT,
    INFRASTRUCTURE_PROMPT,
)

__all__ = [
    "TECHNOLOGY_STACK_PROMPT",
    "SYSTEM_ARCHITECTURE_PROMPT",
    "DATABASE_DESIGN_PROMPT",
    "API_SPECIFICATION_PROMPT",
    "TRD_SUMMARY_PROMPT",
    "SECURITY_REQUIREMENTS_PROMPT",
    "INFRASTRUCTURE_PROMPT",
]
