"""WBS generation prompts."""

from .wbs_prompts import (
    PHASE_GENERATION_PROMPT,
    WORK_PACKAGE_PROMPT,
    TASK_GENERATION_PROMPT,
    RESOURCE_ALLOCATION_PROMPT,
    SCHEDULE_OPTIMIZATION_PROMPT,
    ESTIMATION_PROMPT,
)

__all__ = [
    "PHASE_GENERATION_PROMPT",
    "WORK_PACKAGE_PROMPT",
    "TASK_GENERATION_PROMPT",
    "RESOURCE_ALLOCATION_PROMPT",
    "SCHEDULE_OPTIMIZATION_PROMPT",
    "ESTIMATION_PROMPT",
]
